#!/usr/bin/env python3
"""Generate the view payload the JS tests read — with the REAL exporter.

    make ui-fixture                     # rewrite ui/tests/fixtures/assembled.json
    make ui-fixture-data                # ...and publish a build into data/ for `make run`

WHY A GENERATOR AND NOT A HAND-WRITTEN JSON. The file this writes is the
contract between the hub's build half and the browser: `{name, color, parts:
[...]}` all the way down, with a mesh on every leaf. A hand-written stand-in
would freeze somebody's IDEA of that shape, and it would go stale in silence —
`ocp_tessellate` renames a field, the adapter is updated to match, and the JS
suite stays green against a document no build produces any more. Everything
below therefore goes through the same two functions a real build calls,
`prepare_views()` and `export_views()` in src/cadbuild/views.py, so the fixture
is output rather than an impression of it.

    tests/test_view_fixture.py is the other half of that: it re-runs this
    generator and compares the STRUCTURE of the result with the committed file,
    so the day the exporter's shape changes is the day the suite says so.

WHY THE COMMITTED PAYLOAD IS THE ARTEFACT, rather than generating it at test
time. The JS suite runs in a `node:22-bookworm-slim` container in CI, where
there is no Python at all, let alone CadQuery — and on a workstation the kernel
is only there if the dev dependencies were installed. A fixture generated on the
fly would therefore be a JS suite that cannot run in the place it has to run.
The committed file is ~150 KB (17 KB over the wire — it is JSON full of
repeating float text and compresses ten to one), which is a rounding error next
to the 3.5 MB vendored viewer already in this repository.

WHAT THE MODEL IS AND WHY IT IS THIS ONE. Small enough to commit, and
deliberately not degenerate:

  * FOUR PARTS, not one — the part tree has to be a tree with siblings, and the
    hidden/ghost/select code in ui/src/viewport/parts.js works by path prefix,
    which one node cannot exercise;
  * FLAT FACES on every part, because the section tool takes its plane from the
    normal of a face somebody clicked;
  * SOMETHING CURVED on every part (the post's barrel, the holes through the
    plate and the cap), because a mesh with three normals in it would not tell a
    working tessellation from a broken one;
  * THREE PRINTABLES AND ONE PIECE OF SCENERY, so the colours in the file are
    three different palette entries plus the grey `auto_colors()` paints
    anything that is not printed. A file where every part is the same colour
    cannot show that the colour travels per part.

ONE THING IT DELIBERATELY DOES NOT HAVE: NESTING. The tree comes out two levels
deep — a `Group` and one leaf per view part — and that is not a shortcut taken
here, it is what the pipeline can produce. `prepare_views()` takes each part's
`shape` through `as_shapes()`, which requires CadQuery geometry and refuses a
`cq.Assembly` outright, so one view part is always exactly one leaf. (The FORMAT
nests — feed an Assembly straight to `export_three_cad_viewer_js` and it comes
out nested, which is why src/render.py validates to a depth of 64 — but no model
can reach that through views().) The recursion in `treeFromShapes` is covered in
the JS suite against a tree built by nesting these real leaves, with the
difference spelled out there.

REGENERATING IT. `make ui-fixture` from the repository root, then commit the
result. Needs the CAD kernel, so `make install` first on a machine that has not
had it. The mesh depends on the pinned `cadquery`/`ocp-tessellate` versions, so
a diff bigger than a few floats after an unrelated change is worth reading
rather than committing blind — that IS the drift this file exists to make
visible.
"""

import argparse
import io
import json
import sys
import tarfile
import tempfile
import time
from pathlib import Path

# ui/tests/fixtures -> ui/tests -> ui -> the repository root.
ROOT = Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

HERE = Path(__file__).resolve().parent

# The one view the JS suite reads. `print` is generated too (a real project has
# both, and the pipeline gates them differently), but only this one is committed:
# the suite needs a payload, not a catalogue, and the second file would double
# the bytes in the repository to say nothing new.
FIXTURE_VIEW = "assembled"
FIXTURE_PATH = HERE / f"{FIXTURE_VIEW}.json"

# What `make ui-fixture-data` publishes under. `dev` is the hub's local slot,
# which is the right one for something a person is about to look at: it is
# served `no-cache` and every push rewrites it, so re-running this never piles
# builds up in data/.
FIXTURE_PID = "fixture0000"
FIXTURE_TITLE = "Fixture model (generated by ui/tests/fixtures/make_fixture.py)"


def model():
    """The model, in the shape a project's model.py hands over.

    Returns `(views, printables)` — exactly the two things `build()` reads out
    of a model.py, so what happens to them below is what happens to a real one.
    """
    import cadquery as cq

    # ONE curved feature per part, and no more, because every one of them is
    # paid for in the committed file: a hole is a cylindrical wall plus two
    # discretised circles, and the tessellator writes those out as
    # full-precision floats. Two holes in the plate instead of one cost 18 KB on
    # their own — measured, by generating both. What the fixture needs is that
    # curvature is PRESENT on every part, not that there is a lot of it.
    #
    # The plate: flat top and bottom for the section tool, one bore for the mesh.
    plate = (cq.Workplane("XY").box(24, 16, 3)
             .faces(">Z").workplane().hole(3))
    # The barrel. Nothing but curvature and two flat ends.
    post = cq.Workplane("XY").circle(4).extrude(12)
    # A cap with a bore, so the tree holds two parts that are similar without
    # being the same solid — the colour matcher fingerprints by volume and face
    # areas, and two identical solids would let it paint either one either way.
    cap = (cq.Workplane("XY").box(12, 12, 3)
           .faces(">Z").workplane().hole(5))
    # NOT printed: a bought part, the kind a real assembly shows for reference.
    # It is what makes one leaf of the fixture grey while the other three carry
    # palette colours. A plain disc rather than a washer with its bore: the bore
    # was the single most expensive feature in the file (a tube is two
    # cylindrical walls and four circles, 71 KB of the first 221 KB version) and
    # bought nothing the plate's hole does not already cover.
    spacer = cq.Workplane("XY").circle(5).extrude(1)

    printables = {"plate": plate, "post": post, "cap": cap}

    assembled = {
        "id": FIXTURE_VIEW,
        "name": "assembled",
        "parts": [
            {"shape": plate, "name": "plate"},
            {"shape": post.translate((0, 0, 1.5)), "name": "post"},
            {"shape": cap.translate((0, 0, 15)), "name": "cap"},
            # Half transparent, because the fixture should carry an alpha that
            # is not 1: `defaultOpacity` and the per-part transparency path in
            # parts.js are the two places a stray 1.0 would hide.
            {"shape": spacer.translate((0, 0, 3)), "name": "reference spacer",
             "alpha": 0.6},
        ],
    }
    # The print plate. Laid out with clear air between the parts, because
    # check_print_layout() refuses a pile — and a fixture that could not pass
    # the gates it is generated behind would be a fixture of nothing.
    printed = {
        "id": "print",
        "name": "as printed",
        "parts": [
            {"shape": plate, "name": "plate (print)"},
            {"shape": post.translate((22, 0, 0)), "name": "post (print)"},
            {"shape": cap.translate((-22, 0, 0)), "name": "cap (print)"},
        ],
    }
    return [assembled, printed], printables


def export(out_dir):
    """Run the model through the real pipeline. Returns the meta.json entries.

    The three calls are the ones `src/cadbuild/build.py` makes in this order,
    minus the halves a viewer payload has nothing to do with (the STL/3MF
    exports, the PNG previews and the metrics file). The two GATES are kept
    deliberately even though nothing here would fail them today: they are what
    makes the fixture a payload a real build would have accepted, rather than
    one that happens to tessellate.
    """
    from src.cadbuild.gate import check_print_layout, check_printables_shown
    from src.cadbuild.views import export_views, prepare_views

    views, printables = model()
    prepared = prepare_views(views, printables)
    check_print_layout(prepared)
    check_printables_shown(prepared, printables)
    out_dir.mkdir(parents=True, exist_ok=True)
    return export_views(prepared, out_dir)


def write_fixture(out_dir):
    """Copy one exported view out of `out_dir` and over the committed fixture."""
    source = out_dir / f"{FIXTURE_VIEW}.json"
    # Byte-for-byte what the exporter wrote. Not re-serialised through
    # json.dumps() with indentation: a fixture that had been through somebody's
    # pretty-printer is no longer evidence of what the exporter emits, which is
    # the only reason this file exists.
    FIXTURE_PATH.write_bytes(source.read_bytes())
    print(f"{FIXTURE_PATH.relative_to(ROOT)}: "
          f"{FIXTURE_PATH.stat().st_size / 1024:.1f} KB")


def meta_json(entries):
    """The meta.json a push carries beside its views.

    Only the fields src/render.py reads: it normalises the rest itself and
    rejects anything it does not recognise, so writing more would be guessing.
    """
    return {
        "project": "fixture",
        "title": FIXTURE_TITLE,
        "built": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "views": entries,
        "downloads": {},
    }


def publish_to_data(out_dir, entries, data_dir):
    """Put a real build in `data/` so `make run` has something to show.

    Through the hub's OWN store rather than by writing the directory by hand.
    `Store.publish_dev()` is what an actual push ends in — it unpacks the tar,
    validates every view file, writes the normalised meta.json and the payload
    digest — so what lands under data/ is a build the hub made, not an
    imitation of one that would diverge the first time the layout changed.

    The SAME export the fixture came out of, handed in rather than recomputed:
    a second tessellation would take twice as long to produce a build that is
    only nearly the file the JS suite reads.
    """
    from src.store import Store

    (out_dir / "meta.json").write_text(
        json.dumps(meta_json(entries), indent=2) + "\n", encoding="utf-8")

    # The push format: one gzipped tar of the build directory's contents.
    blob = io.BytesIO()
    with tarfile.open(fileobj=blob, mode="w:gz") as tar:
        for path in sorted(out_dir.iterdir()):
            tar.add(path, arcname=path.name)
    body = out_dir / "body.tar.gz"
    body.write_bytes(blob.getvalue())

    store = Store(data_dir, retention_builds=20,
                  max_build_bytes=64 * 1024 * 1024)
    status, answer = store.publish_dev(FIXTURE_PID, body, body.stat().st_size)
    print(f"published {status} into {data_dir}: {answer.get('url', '')}")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--data", metavar="DIR",
        help="also publish a full build into this hub data directory "
             "(default: nothing is written outside ui/tests/fixtures/)")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as scratch:
        out_dir = Path(scratch) / "out"
        entries = export(out_dir)
        write_fixture(out_dir)
        if args.data:
            publish_to_data(out_dir, entries, Path(args.data).resolve())


if __name__ == "__main__":
    main()
